//Selectores para DOM
export const nombreCompleto = document.getElementById('nombre')
export const pais = document.getElementById('pais')
export const edad = document.getElementById('edad')
export const carrera = document.getElementById('carrera')
export const email = document.getElementById('email')
export const btnAgregar = document.getElementById('btn')
export const form = document.getElementById('form')
export const container_citas = document.querySelector('#resultados_citas')
export const selectOption = document.querySelector('select')
